---

- name: install lighttpd 
  yum:
    name: lighttpd
    state: present
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"
  tags: lighttpd

- name: ensure a list of lighttpd packages installed 
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - lighttpd-fastcgi
    - lighttpd-mod_authn_mysql
    - lighttpd-mod_geoip
    - lighttpd-mod_mysql_vhost
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7" 
  tags: lighttpd


- name: install lighttpd 
  dnf:
    name: lighttpd
    state: present
  when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8") or (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "9")
  tags: lighttpd

- name: ensure a list of lighttpd packages installed 
  dnf:
    name: "{{ packages }}"
  vars:
    packages:
    - lighttpd-fastcgi
    - lighttpd-filesystem
    - lighttpd-mod_authn_gssapi
    - lighttpd-mod_openssl
    - lighttpd-mod_authn_pam
    - lighttpd-mod_authn_sasl
    - lighttpd-mod_gnutls
    - lighttpd-mod_deflate
    - lighttpd-mod_vhostdb_mysql
  when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8") or (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "9") 
  tags: lighttpd
  
- name: enable lighttpd service
  systemd:
    name: lighttpd
    enabled: yes
  tags: lighttpd
  
- name: Make sure lighttpd service is running
  systemd:
    state: started
    name: lighttpd
  tags: lighttpd

- name: adding firewall rules http for lighttpd service
  firewalld: 
    service: http
    permanent: true
    state: enabled
  notify: Reloading firewalld rules
  tags: lighttpd

- name: adding firewall rules https for lighttpd service
  firewalld: 
    service: https
    permanent: true
    state: enabled
  notify: Reloading firewalld rules
  tags: lighttpd

- name: Backup lighttpd.conf if it differs from the copied version
  copy:
    src: /etc/lighttpd/lighttpd.conf
    dest: /etc/lighttpd/lighttpd.conf.bck
    owner: root
    group: root
    mode: '0644'
    remote_src: yes
    backup: yes
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7" 
  tags: lighttpd


- name: Ensure server.use-ipv6 is set to disable into lighttpd.conf
  replace:
    path: /etc/lighttpd/lighttpd.conf
    regexp: '^server.use-ipv6 = "enable"'
    replace: server.use-ipv6 = "disable"
  notify: Reloading lighttpd
  tags: lighttpd


- name: Ensure server.bind is set to listen different from localhost
  replace:
    path: /etc/lighttpd/lighttpd.conf
    regexp: '^#server.bind = "localhost"'
    replace: server.bind = "0.0.0.0"
  notify: Reloading lighttpd
  tags: lighttpd


- name: Backup modules.conf if it differs from the copied version
  copy:
    src: /etc/lighttpd/modules.conf
    dest: /etc/lighttpd/modules.conf.bck
    owner: root
    group: root
    mode: '0644'
    remote_src: yes
    backup: yes
  tags: lighttpd


- name: Copy modules_modify_EL7.conf into /etc/lighttpd/
  copy:
    src: modules_modify_EL7.conf
    dest: /etc/lighttpd/modules.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reloading lighttpd
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7" 
  tags: lighttpd

- name: Copy modules_modify_EL8.conf into /etc/lighttpd/
  copy:
    src: modules_modify_EL8.conf
    dest: /etc/lighttpd/modules.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reloading lighttpd
  when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8") or (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "9") 
  tags: lighttpd


- name: Backup fastcgi.conf if it differs from the copied version
  copy:
    src: /etc/lighttpd/conf.d/fastcgi.conf
    dest: /etc/lighttpd/conf.d/fastcgi.conf.bck
    owner: root
    group: root
    mode: '0644'
    remote_src: yes
    backup: yes
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7" 
  tags: lighttpd


- name: Copy fastcgi_modify_EL7 into /etc/lighttpd/conf.d/
  copy:
    src: fastcgi_modify_EL7.conf
    dest: /etc/lighttpd/conf.d/
    owner: root
    group: root
    mode: '0644'
  notify: Reloading lighttpd
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7" 
  tags: lighttpd


- name: Copy fastcgi_modify_EL8 into /etc/lighttpd/conf.d/
  copy:
    src: fastcgi_modify_EL8.conf
    dest: /etc/lighttpd/conf.d/
    owner: root
    group: root
    mode: '0644'
  notify: Reloading lighttpd
  when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8") or (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "9")  
  tags: lighttpd

- name: Install python3-libsemanage
  package:
    name: python3-libsemanage
    state: present
  when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8") or (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "9") 
  tags: lighttpd


- name: Install libsemanage-python
  package:
    name: libsemanage-python
    state: present
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"
  tags: lighttpd  

- name: Set httpd_setrlimit flag on and keep it persistent across reboots
  seboolean:
    name: httpd_setrlimit
    state: yes
    persistent: yes
  tags: lighttpd
  
- name: restart service lighttpd
  systemd:
    state: restarted
    name: lighttpd
  when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8") or (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "9") 
  tags: lighttpd
  
