---

- name: Include variable
  include_vars:
    file: vars.yml

- name: Install a list of php7.2 packages
  dnf:
    name: "{{ packages }}"
  vars:
    packages:
    - php 
    - php-mysqlnd 
    - php-gd 
    - php-pdo
    - php-mbstring
    - php-fpm 
  tags: php7


- name: Backup /etc/php.ini if it differs from the copied version
  copy:
    src: /etc/php.ini
    dest: /etc/php.ini.bck
    owner: root
    group: root
    mode: '0644'
    remote_src: yes
    backup: yes
  tags: php7


- name: enable php-fpm service
  systemd:
    name: php-fpm
    enabled: yes
  tags: php7
  
- name: Make sure php-fpm service is running
  systemd:
    state: started
    name: php-fpm
  tags: php7


- name: Copy www_modify.conf file to /etc/php-fpm.d/
  copy:
    src: www_modify.conf
    dest: /etc/php-fpm.d/www.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reloading php-fdm service
  tags: php7


- name: Template php-ini.j2 file to /etc/php.ini
  template:
    src: php-ini.j2
    dest: /etc/php.ini
    owner: root
    group: root
    mode: '0644'
  notify: Reloading lighttpd service
  tags: php7