---


- name: Remove centos-release-scl  
  yum:
    name: centos-release-scl
    state: absent
  when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7")
  tags: php

- name: Remove a list of php packages
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - rh-php73 
    - rh-php73-php
    - rh-php73-php-common
    - rh-php73-php-mysqlnd
    - rh-php73-php-odbc
    - rh-php73-php-json
    - rh-php73-php-pear
    - rh-php73-php-mbstring
    - rh-php73-php-gd
    - rh-php73-php-fpm
    - rh-php73-php-intl
    - rh-php73-php-pdo
    - rh-php73-php-xml
  when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7") 
  tags: php


- name: Remove scl_enable.sh file from /etc/profile.d
  file:
    path: /etc/profile.d/scl_enable.sh
    state: absent
  when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7") 
  tags: php


- name: Remove a list of php packages
  dnf:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - php 
    - php-mysqlnd
    - php-gd
    - php-gmp
    - php-json
    - php-pear
    - php-fpm
    - php-mbstring
    - php-odbc
    - php-pdo
    - php-pear
    - php-process
    - php-xml
    - php-common
    - php-intl
  when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8") or (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "9") 
  tags: php