---

- name: upgrade all packages 
  dnf:
    name: "*"
    state: latest
  tags: upgrade  


- name: ensure a list of packages installed
  dnf:
    name: "{{ packages }}"
  vars:
    packages:
    - wget
    - curl
    - bash-completion
    - vim
    - zip
    - bzip2
    - gzip
  tags: package


- name: Install epel package
  package:
    name: epel-release
    state: present
  tags: package

- name: install htop 
  dnf:
    name: htop
    state: present
  tags: package  

