---


- name: disable lighttpd service
  systemd:
    name: lighttpd
    enabled: no
  tags: lighttpd
  
- name: Make sure lighttpd service is stopped
  systemd:
    state: stopped
    name: lighttpd
  tags: lighttpd

- name: Remove lighttpd 
  dnf:
    name: lighttpd
    state: absent
  tags: lighttpd


- name: Remove lighttpd 
  yum:
    name: lighttpd
    state: absent
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"
  tags: lighttpd

- name: ensure a list of lighttpd packages removed 
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - lighttpd-fastcgi
    - lighttpd-mod_authn_mysql
    - lighttpd-mod_geoip
    - lighttpd-mod_mysql_vhost
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7" 
  tags: lighttpd


- name: Remove lighttpd 
  dnf:
    name: lighttpd
    state: absent
  when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8") or (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "9")
  tags: lighttpd

- name: ensure a list of lighttpd packages removed 
  dnf:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - lighttpd-fastcgi
    - lighttpd-filesystem
    - lighttpd-mod_authn_gssapi
    - lighttpd-mod_openssl
    - lighttpd-mod_authn_pam
    - lighttpd-mod_authn_sasl
    - lighttpd-mod_gnutls
    - lighttpd-mod_deflate
    - lighttpd-mod_vhostdb_mysql
  when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8") or (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "9") 
  tags: lighttpd


- name: Removing firewall rules http for lighttpd service
  firewalld: 
    service: http
    permanent: true
    state: disabled
  notify: Reloading firewalld rules
  tags: lighttpd

- name: Removing firewall rules https for lighttpd service
  firewalld: 
    service: https
    permanent: true
    state: disabled
  notify: Reloading firewalld rules
  tags: lighttpd

- name: Recursively remove directory /etc/lighttpd/l
  file:
    path: /etc/lighttpd/
    state: absent
  tags: lighttpd


- name: Recursively remove directory /etc/lighttpd/l
  file:
    path: /var/cache/lighttpd
    state: absent
  tags: lighttpd


- name: Set httpd_setrlimit flag off and keep it persistent across reboots
  seboolean:
    name: httpd_setrlimit
    state: no
    persistent: no
  tags: lighttpd
  



